### ISSUE TITLE
onfinish in createSound does not fire properly

### ISSUE THREAD

**Issue by jjatria** [scottschiller/SoundManager2#102]
[This demo](http://www.megatrax.com/soundManager/demo/api/#demo2) showcases the problem.

With code like this:

```
var demo2Sound = soundManager.createSound({
 id:'mySound4',
 url:'../mpc/audio/CHINA_1.mp3',
 onfinish:function() {
   soundManager._writeDebug(this.sID+' finished playing');
 }
});
demo2Sound.play({volume:50});
```

the sound will play, but the debug message will never be printed.

Or is there something obvious I'm missing?

**Comment by scottschiller** [comment]
Howdy! (Sorry for late follow-up.)

The demo here works OK for me in HTML5 and Flash, I do get the "finished playing" debug message. 
http://www.megatrax.com/soundManager/demo/api/#demo2

What browser/device/platform are you running into the issue on?

**Comment by scottschiller** [comment]
A late update - there's an issue which I suspect is related, which has a repro that applies to mobile Safari (iOS) and is confirmed.

I'm going to close this in favour of taking on the report here - https://github.com/scottschiller/SoundManager2/issues/158 - if the report here is a different case, feel free to reopen!
