### ISSUE TITLE
[bar-ui.js] Next button doesn't work when multiple songs have download buttons

### ISSUE THREAD

**Issue by nickyr** [scottschiller/SoundManager2#104]
If you have a player using bar ui and all of the songs have download buttons, the next button doesn't work. The fix is to add 
```
item = liElement;
```
at the end of the if block in the select() function in bar-ui.js (line 560).

**Comment by scottschiller** [comment]
Ah-ha! Thanks. Will work this in for the next release.

**Comment by nickyr** [comment]
:+1:

**Comment by tchoulihan** [comment]
This is still a problem for me, I'm going to try the fix now.

**Comment by scottschiller** [comment]
Reminder to self - get the next release out sooner than later. :grin:
