### ISSUE TITLE
How can I check whether the file or not?

### ISSUE THREAD

**Issue by vtur** [scottschiller/SoundManager2#108]
Hello, I want to check if a file exists, if Yes then play it, if not, then perform other actions. 
Question: is there a way to check file audio file to exist?

**Comment by scottschiller** [comment]
When you attempt to load or play the file, SM2 will fire an `onload()` event that includes a boolean inferring load success.

e.g.,
```javascript
mySound.play({
  onload: function(ok) {
    if (!ok) {
      // hmm. show error?
    }
  }
});
```

Alternately, if you have same-domain or CORS rights etc., you can check this stuff by using a HEAD request via XHR. You can look at the HTTP response, and a non-`404` (i.e., a `200`) should infer that the file is present. It doesn't mean that SM2 will be able to necessarily _play_ it as that depends on support for the format in question, but it's a start.

Example:
http://stackoverflow.com/questions/333634/http-head-request-in-javascript-ajax
