### ISSUE TITLE
HTML5 mode (Firefox): bytesLoaded property stays below bytesTotal

### ISSUE THREAD

**Issue by wo80** [scottschiller/SoundManager2#114]
I have tested this with the latest Firefox and mp3 audio. It might be regarded a Firefox bug (haven't checked bugzilla), but it would be nice to see a workaround in Soundmanager2.

The problem:
In HTML5 mode, while the audio loads, the `bytesLoaded` property increases from 0 to `bytesTotal`. But quite regularly, it will not reach `bytesTotal` but stop at a value less than `bytesTotal`. This is annoying if you display some info about the loading progress.

You can test this in Firefox without using Soundmanager:

``` javascript
var el = document.getElementById('audio');

el.addEventListener('progress', function() {
    console.log({name: 'progress', buffered: el.buffered.end(el.buffered.length - 1)});
});

el.addEventListener('timeupdate', function() {
    console.log({name: 'timeupdate', buffered: el.buffered.end(el.buffered.length - 1)});
});
```

Just test a couple of files. Sooner or later you'll get something like

```
name: "progress", buffered: 2.658047
name: "progress", buffered: 4.451929
[...]
name: "progress", buffered: 261.747545
name: "progress", buffered: 269.709077
```

But when you start the sound, you see that the total length is actually higher:

```
name: "timeupdate", buffered: 271.512068
```

So, in Soundmanager2, you might not want to rely on the `progress` event alone to update the `bytesLoaded` property.

**Comment by scottschiller** [comment]
Thanks for the detail, pardon the month-late reply. :stuck_out_tongue_closed_eyes: 
The `bytesLoaded` / `bytesTotal`, time and progress stuff is a little funny in HTML5 as implementations vary a bit between browsers; I try to normalize everything, but it's tricky. I also cannot presume (IIRC) that all bytes are loaded even when the HTML5 `loaded` event fires, because HTML5 by default uses partials / range requests and so on.

This sounds like a Firefox-specific issue, but something I may be able to work around easily enough by looking at `timeupdate` as you suggest. Thanks.

**Comment by scottschiller** [comment]
FWIW I've pushed V2.97a.20170601 live; do let me know if you continue seeing mis-matches of `bytesLoaded` / `bytesTotal` disrepancies. I suspect with the passing of time, things may have been patched up within Firefox itself. 🤞 

(And, please re-open if this still applies!)

**Comment by paulijar** [comment]
@scottschiller This problem is still present in V2.97a.20170601 and up-to-date Firefox 56.0.

You might be interested on the application-side workaround which was implemented for ownCloud Music in https://github.com/owncloud/music/pull/587.

**Comment by fascinated** [comment]
Just a quick note on this weird one - it's still possible to reproduce in newer Firefox, like 67.0. The issue isn't present in a default install, but if you use Ghostery (and maybe other ad block-style extensions), this bytesLoaded issue shows up. So probably not a SM2 problem, but just FYI.
