### ISSUE TITLE
Play from: doesn't start at proper position in Chrome, works in Safari

### ISSUE THREAD

**Issue by bildlich** [scottschiller/SoundManager2#115]
I am using HTML playback to play portions of a ~50 minute / 55 MB mp3 file.
In Chrome, the playback consistently starts a few seconds off. In different files the offset is different: sometimes the playback starts a few seconds too early, sometimes too late. In Safari and Firefox, all is fine.

The soundObject is instantiated like this:

      soundObject = soundManager.createSound({
        id: erik-spiekermann-onl,
        url: urlToMyFile,
        autoLoad: false,
        autoPlay: false
      });

A sound portion is played like this:

          soundObject.play({from: fragment.start, to: fragment.end}); // fragment.start and fragment.end are timecodes in ms

The log output in DebugMode looks the same for Safari and Chrome:

    [Log] erik-spiekermann-onl: play(): Attempting to load (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: load (/assets/local-mp3/erik-spiekermann-onl.mp3) (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: play(): Beginning load for non-zero offset case (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: load (/assets/local-mp3/erik-spiekermann-onl.mp3) (vendor.js, line 1295)
    [Info] soundManager.load(): current URL already assigned. (vendor.js, line 1293)
    [Log] erik-spiekermann-onl: loadstart (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: durationchange (3390066.93877551) (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: loadedmetadata (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: progress, 100% loaded (vendor.js, line 1295)
    [Info] erik-spiekermann-onl: onload() (vendor.js, line 1293)
    [Log] erik-spiekermann-onl: suspend (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: loadeddata (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: canplay (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: play() (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: Playing "from" 89752 (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: setPosition(89.752) (vendor.js, line 1295)
    [Log] erik-spiekermann-onl: playing ♫ (vendor.js, line 1295)
    [Log] current position: 89752 (script.js, line 1103)
    [Log] current position: 89872.971631 (script.js, line 1103)

The last two lines are logged by me. In the `whileplaying` function I log `this.position`. It outputs the exact position it is supposed to start from.

**Comment by bildlich** [comment]
The error occurs only in Chrome Stable (47.0.2526.106). I just tested Chrome Canary (49.0.2612.0) and there it works. Since this is clearly a Chrome issue, I am closing this.

**Comment by scottschiller** [comment]
Thanks for the report, since others may also have run into similar behaviour.

**Comment by bbshopadmin** [comment]
I encountered the same issue in Chrome 59.0.3071.115. Is there a workaround?

**Comment by scottschiller** [comment]
This might be an issue with longer MP3s where seeking can "slip" a bit (?) somehow, or perhaps it's specific to the way the MP3 is encoded.

SM2 has no real control over HTML5 playback, it merely sets the relevant position offset attribute on the `<audio>` element and the browser takes it from there.
