### ISSUE TITLE
Sound playback position calculated to be half of what it actually is in Safari

### ISSUE THREAD

**Issue by trostli** [scottschiller/SoundManager2#122]
For the player I am building, I would like visual feedback of the playback position. Chrome and Firefox seem to correctly report the playback position so I can calculate the percentage played but in Safari it seems the position being reported back is half of what it should be.

**Comment by scottschiller** [comment]
Interesting. Perhaps it's specific to the MP3 (?) / content in question, possibly related to the way it's encoded. If you drop the file directly into the browser and let it play the audio directly, does the built-in player UI show similar behaviour?

**Comment by trostli** [comment]
Hmm thanks for suggesting that because the built in safari player has the same behaviour. It miscalculates the duration the 1st time and then on subsequent plays it correctly estimates duration.

**Comment by scottschiller** [comment]
Ah-ha, that would suggest the issue is between the MP3 and Safari's HTML5 decoding - yup. If you can, try getting a different version of that MP3.
