### ISSUE TITLE
No callbacks executed in Opera 35 (Windows XP)

### ISSUE THREAD

**Issue by outaTiME** [scottschiller/SoundManager2#126]
Hi folks, 

Im using SM2 for a long time, but today i found an error when trying to load the library in Opera 35, but only in Windows XP in other OS works as expected, here my configuration ... no `onready` / `ontimeout` callback executed =(

(again, its a functional code works in all other environments, probably something related to windows xp)

``` js
soundManager.setup({
  url: '/bower_components/soundmanager/swf/',
  debugMode: true,
  onready: function () {
    console.log('SoundManager loaded...');
  },
  ontimeout: function() {
    console.error('Error loading SoundManager...');
  }
});
```

ideas ??

thks !!

**Comment by outaTiME** [comment]
Here debug from sm2:

![screen shot 2016-02-22 at 11 00 25 pm](https://cloud.githubusercontent.com/assets/140472/13239313/17de6d78-d9b8-11e5-8aad-21ceaf1960ca.png)

**Comment by outaTiME** [comment]
in this scenario would not have to run `ontimeout` callback ??

**Comment by outaTiME** [comment]
Here debug from same opera version running on macos:

```
SoundManager 2: No Flash detected. Trying HTML5-only mode.
SoundManager V2.97a.20150601 (HTML5-only mode)
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true
```

**Comment by outaTiME** [comment]
BTW, here debug from Google Chrome running in Windows XP:

```
SoundManager V2.97a.20150601 (HTML5-only mode)
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true
SoundManager 2: Ready. ✓
```

It works as expected ...

**Comment by outaTiME** [comment]
Any update ??

**Comment by scottschiller** [comment]
Sorry, I guess I must just not be thinking fourth-dimensionally! :laughing:

This _might_ be related to a previous issue, where Opera lacks MP3 support via HTML5 for a number of reasons.
https://github.com/scottschiller/SoundManager2/issues/110

With Opera on WinXP, you are arguably using 1985-era tech; support may be limited. XP has long been out of official support by MSFT, as well. That said, I wrote SM2 originally to run on WinXP, so it should still work reasonably well on that OS. I think the issue lies with Opera in this case, where it doesn't support MP3 via HTML5 because MP3 is technically not a "free" format.

Will update when I've confirmed in a VM, here.

**Comment by scottschiller** [comment]
Here's output from Opera 35 on WinXP:
`SoundManager 2 HTML5 support: mp3 = false (using flash), mp4 = false (using flash), ogg = true, opus = true, wav = true`

So, that's that. No native HTML5 support for MP3, which means you need the Flash plug-in installed for MP3 (and/or MP4) support. MP4 is not required under SM2, but MP3 is.

If you don't need MP3, you can set `soundManager.audioFormats.mp3.required = false`; - see [audioFormats](http://www.schillmania.com/projects/soundmanager2/doc/#soundmanager-audioformats) for detail.

**Comment by outaTiME** [comment]
Great Scott :laughing: 

But ... why ontimeout callback never executed? 

I need to intercept this escenario to continue my application flow ... throwing for example an warning for that ...

**Comment by scottschiller** [comment]
Heh.
So, this _might_ be an edge case - but SM2 should fire the `ontimeout` event when it can't load Flash. It looks like the SM2 basic demo fires that event in Opera 35 on WinXP, and it also uses the same `setup()` method.

Any chances you are calling `soundManager.setup()` later in your app, like after DOMReady or something? It's unlikely, but there may be a chance of a timing/race condition in this specific scenario. Once the SM2 JS has loaded, it will start up ASAP so it's best if you call `setup()` immediately afterward.

Worst-case, if you don't get the `onready()` callback from SM2 you can also check `soundManager.ok()` at any time and it will tell you if it has failed to start / cannot play sounds. So the first time you try to play a sound, you could check then and warn the user.

**Comment by outaTiME** [comment]
Yup probably `soundManager.setup()` its called after DOMReady ... im loading a few javascript in async way ... when all loaded im setup the `soundManager` ... 

Im using this way for a while in any other browser / OS works as expected ... particularly in this opera case we need to execute  `soundManager.setup()` before on DOMReady?

In the past im using the old `soundManager` using their async load way ... but it doesn't work too in my escenario (for opera in winxp of course):

http://www.schillmania.com/projects/soundmanager2/demo/template/sm2_defer-example.html

**Comment by outaTiME** [comment]
Hi Scott, any updates with this ?

thks !!!

**Comment by scottschiller** [comment]
Testing now with Opera 36.

Interestingly, I get a little green box prompting me to install Flash on the SM2 homepage with this browser, now.

After an install of Flash and a restart of the browser, I see "Couldn't load plugin" in the place where the Flash player plugin should be shown. Very strange.

If you can get a Flash install working with the latest Opera (36?) on Windows XP, let me know - but this OS has long been out of support, now, and is likely highly vulnerable to remote security attacks.

**Comment by outaTiME** [comment]
Yup, you are right ...

what happens if i convert the mp3 file to ogg format, it will solve this issue? which it is the support ogg file on browsers / platforms?

**Comment by scottschiller** [comment]
I'd expect OGG to work. You'll need to set MP3 as a non-"required" format for SM2 to start in this case then, under Opera in particular.

**Comment by outaTiME** [comment]
how ?

**Comment by scottschiller** [comment]
Try setting `soundManager.audioFormats.mp3.required = false;` before calling `setup()`.

**Comment by scottschiller** [comment]
V2.97a.20170601 is out, mostly a support release - minor tweaks and whatnot. A check for FLAC has been added as well to the default formats.

WinXP and Opera are increasingly small these days, but do let me know if you see events firing (or not) with the latest. Reopen as necessary.
