### ISSUE TITLE
Can't drag the progress bar on Bar UI

### ISSUE THREAD

**Issue by zangbianxuegu** [scottschiller/SoundManager2#129]
Is there no touch events for Bar UI ?

**Comment by samayo** [comment]
It works for me, what exactly are you having problems with?

**Comment by scottschiller** [comment]
Apologies for super-late reply, have been very busy with professional work. 😅 

I don't think tap-and-drag (click-and-drag), i.e., scrubbing the progress bar works, and I could probably improve on that. It just takes click events and will attempt to jump to the target position, or as far as the sound has loaded at present.

**Comment by Local9** [comment]
In my experience, its when using Chrome with HTML5 but only if the file is being streamed. Firefox is fine and well we don't support IE internally so I haven't tested it.

**Comment by scottschiller** [comment]
I'm adding `touch` events for this shortly - stay tuned.

**Comment by scottschiller** [comment]
(Should now be working; this will go out with the next release.)
