### ISSUE TITLE
How to detect when next song is played.

### ISSUE THREAD

**Issue by samayo** [scottschiller/SoundManager2#132]
I would like to know if there is anything I can do when SM is playing the next song by itself. As in, if I have 10 songs and it plays one after the other, how can I get a simple notice. I am tying to attach a middleware between the end of one song and the beginning of the next and it would be nice to know.

**Comment by scottschiller** [comment]
Apologies for super-late reply, have been very busy with professional work. 😅

I recommend hooking into the `onfinish` event, called each time a sound playback completes.

eg.,
```
mySound.play({
  // where `this` = the sound object in question
  onfinish: function() { console.log('yay, done!', this);
});
```

**Comment by scottschiller** [comment]
Presuming this is resolved, `onfinish` is detailed.
http://www.schillmania.com/projects/soundmanager2/doc/#smsound-onfinish
