### ISSUE TITLE
SoundManager2 doesn't work on iOS 10

### ISSUE THREAD

**Issue by fremail** [scottschiller/SoundManager2#140]
```
soundManager.createSound({
    url: 'url to mp3 file'
});
```
This calling returns false.
Also there is a message in a browser console:
```
> soundManager.createSound(): Audio support is not available.
```

The same behavior in Safari and in Chrome.

**Comment by fremail** [comment]
I had an old version of a SoundManager where `ua.match(/os (1|2|3_0|3_1)/i)` is used instead of `ua.match(/os (1|2|3_0|3_1)\s/i)`

**Comment by scottschiller** [comment]
Sorry about this one, you are correct - see the 20140901 update for details. 🙈 😂 http://www.schillmania.com/projects/soundmanager2/doc/download/#sm2-20140901
