### ISSUE TITLE
On mobile browser: add more track then current playing to be pause

### ISSUE THREAD

**Issue by vinh1508** [scottschiller/SoundManager2#144]
I have to try on mobile browser and add new track to playlist then current track playing is can't play.

**Comment by scottschiller** [comment]
Sorry for late reply, Vinh -

Perhaps something is causing the current track to stop and start playing again when updating the playlist? Because of mobile restrictions, you basically cannot touch the currently-playing sound and have to wait for its `onfinish()` event callback to start playing the next one.

**Comment by realgsong** [comment]
@scottschiller   Hi Scott. Can you reopen this bug? I have same issue and did some debuggins and have some questions.

At 
 https://github.com/scottschiller/SoundManager2/blob/227dd0aaea1520787075fe73b9b7f52bc8be35a1/script/soundmanager2.js#L547

createSound always call _setup_html5 in case of html5ok() and  _setup_html5 stops current playing sound if it's global html audio. See below.  

https://github.com/scottschiller/SoundManager2/blob/227dd0aaea1520787075fe73b9b7f52bc8be35a1/script/soundmanager2.js#L3069

This causes createSound to stop currently playing audio which is used in a library like ngx-soundmanager2. See following.

https://github.com/lfarran/ngx-soundmanager2/blob/ef982fbf7abe8f45ffeac639b92b9491682970e2/lib/music-player.service.ts#L249

* Isn't it recommended to call createSound while some other audio is playing? If not, what's proper way to add play list while something is playing.
* Why do we have to call _setup_html5 for newly created sound object?

Well, I'm not sure this is bug of soundmanager2. Excuse for my silly questions in advance.

Thanks

------

I solved this by setting soundManager.setupOptions.ignoreMobileRestrictions to true but still not sure this is correct fix

**Comment by scottschiller** [comment]
I'll review this when I continue working on the 100% HTML5 refactor of SM2 which I started earlier this year. Sorry this is a very late update. 😅 https://github.com/scottschiller/SoundManager2/tree/sm2-html5only

**Comment by Tasvirgaran** [comment]
من با صدای دروغ و فریب و فحشا کاری ندارم در ظمن من بچه ای هم ندارم
چیزی که از بچه های من ساختید نوش جان مادر ولگردشان
