### ISSUE TITLE
soundmanager2 not firing html5 event 'ended'

### ISSUE THREAD

**Issue by ashish-joshi-sr** [scottschiller/SoundManager2#145]
For some unknown reasons the html5 event in my soundmanager2 library is not firing. other events are working fine. if any one can help with what is causing it, may help me resolve.

to get more idea i've given a url over here. http://engagev2.ncryptedprojects.com/

Thanks.

**Comment by scottschiller** [comment]
"Ended" should be reached when the sound stops playback at the end, or when no more data is available. Perhaps check your HTTP responses, if playback is also not completing all the way through as you'd expect.

Helpful for debugging - does this happen with all files, or just some, etc.?

Some notes here on how HTML5 clients request audio, FWIW:
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#client-requests

Apologies for the very late reply on this, also.

**Comment by scottschiller** [comment]
I've got a confirmed report of SM2 not firing "onfinish" in a specific case on mobile (iOS) Safari, which is probably the closest I've got to this one. https://github.com/scottschiller/SoundManager2/issues/158

If HTML5 isn't firing "ended", then there may be a larger issue with the audio asset in terms of playback or encoding that's preventing the client from properly detecting the end of the file.

Closing this in favour of issue 158 which has a repro - but if you have details on an HTML5 "ended" which fails, feel free to reopen or file a new one! 🙇
