### ISSUE TITLE
How to play audio in chunks

### ISSUE THREAD

**Issue by interwap** [scottschiller/SoundManager2#146]
if you've ever tried to download music on soundcloud or tidal using idm (internet download manager), you'll discover that they tend to be serving their audio files in chunks. This make it difficult for idm to grab the file as its served in small kilobytes (250kb). I'm trying to apply the same technique on a project i'm working on but can't get it figured out just yet.

I'm using soundmanager2 to play the audio file (mp3) via a url which reads the file on the server (PHP). How do i get it to play/stream the audio file in partials/chunks

current setup:

`soundManager.setup({
   url: '/devtools/soundmanager2/swf/',
   flashVersion: 9, // optional: shiny features (default = 8)
   preferFlash: false,
   useFastPolling: true,
   useHighPerformance: true,
   onready: function(oStatus) {

     // check if SM2 successfully loaded..
     if (oStatus.success) {

       var mySound = soundManager.createSound({
         id: 'musicplayer',
         url: '/devtools/audio.php?m=aaa',
         stream: true,
         type: 'audio/mp3'
       //
       });

      mySound.play()

  } else {
    // (Optional) Hrmm, SM2 could not start. Show an error, etc.?
  }
  }
});`

opinions and ideas are welcome

**Comment by scottschiller** [comment]
Pardon the late follow-up, here!

Make sure you're on a recent build of SM2 that uses HTML5 audio. By default, SM2 uses HTML5 and it will attempt to make range / partial, byte requests for audio assets. This is driven entirely by the underlying browser; SM2 itself has no control over the way requests are made.

A little more here on how clients request audio, Flash vs. HTML5 etc.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#client-requests

**Comment by scottschiller** [comment]
Closing this one out. V2.97a.20170601 is now out, though this was more about serving up files in slices. I do recommend seeing the above comment about how clients request audio, since SM2 has no control over the HTTP requests - those are ultimately done by HTML5/Flash.
