### ISSUE TITLE
Audio Object Fires an Error on Finish

### ISSUE THREAD

**Issue by robertnealan** [scottschiller/SoundManager2#152]
I'm interested in displaying an error message to users when our media server has an error (corrupt audio file, missing audio file, etc), but it seems as though `ondataerror` doesn't get fired in this situations. Instead I tried adding a listener on the actual audio object, but it looks like this gets fired any time an audio stream finishes. 

Any ideas why this might be the case and/or how to prevent it?

```
[...]
onplay: function() {
    $(soundManager.sounds[soundManager.soundIDs['0']]._a).on('error', (e) => {
        if(e.target.error.code === 4) {
            _this.stop();
            console.log('Player error :(');
         }
    });
},
[...]
```

**Comment by jayepoch** [comment]
Anyone else experiencing this issue? @scottschiller, any ideas?

**Comment by robertnealan** [comment]
@jayepoch Got a reply from Scott via email suggesting it might actually be a browser-related issue, which makes sense as we're listening directly on the actual HTML audio object that SM2 creates to play the sound (meaning this isn't an issue with SM2 throwing an error, but HTML5 audio itself).

**Comment by scottschiller** [comment]
Sorry for late follow-up, here!
The `ondataerror` is legacy stuff from the Flash audio days, and that won't fire under HTML5 audio. There is a newer `onerror` HTML5 audio event which you should be able to hook into, you can use it in the same way you have `onplay` above there.

HTML5 audio errors stem from failure to load, failure to _decode_ (sometimes this can happen during playback if the MP3 etc. is oddly corrupted), or other playback issues.

The client provides an error code, and a message when the `error` event fires. I can probably touch this up to include the message, if provided, in the client as well.

Details on the types here: https://html.spec.whatwg.org/multipage/embedded-content.html#error-codes
```
MEDIA_ERR_ABORTED (numeric value 1)
    The fetching process for the media resource was aborted by the user agent at the user's request.

MEDIA_ERR_NETWORK (numeric value 2)
    A network error of some description caused the user agent to stop fetching the media resource, after the resource was established to be usable.

MEDIA_ERR_DECODE (numeric value 3)
    An error of some description occurred while decoding the media resource, after the resource was established to be usable.

MEDIA_ERR_SRC_NOT_SUPPORTED (numeric value 4)
    The media resource indicated by the src attribute or assigned media provider object was not suitable.
```
