### ISSUE TITLE
SoundManager2 was not working in Chrome Android when DataSaver turned on 

### ISSUE THREAD

**Issue by Anishmprasad** [scottschiller/SoundManager2#156]
when DataSaver turned on. SoundManager2 wouldn't works in chrome Android 

`Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.`

this would happen in console 

please help me from this

**Comment by scottschiller** [comment]
Hi Anish,

If you are attempting to "auto-play" audio, i.e., on load or page display etc., then it is usually going to be blocked by mobile devices. iOS does this basically all the time.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#mobile-device-limitations

For HTML5 audio load and playback to work, you need to call the audio stuff immediately from a user touch/click/gesture, and no `setTimeout()` or other asynchronous stuff is allowed in-between.

**Comment by Anishmprasad** [comment]
thanks 👍

**Comment by pallavi1993** [comment]
soundmanager2 goes to suspend state after reload in mobiles. but i want it to play after reload also without user interaction. how can i do that?

**Comment by scottschiller** [comment]
@pallavi1993 Sorry for late follow-up - I suspect you'll have a sound `suspend` event at that point, actually, probably `pause` (and I need to hook that one up 😅) - the safest thing to do is probably just make sure your UI catches stopped sounds. Most of my UI demos should respond to the `pause` event, but I have to wire that up from the HTML5 event side so it tells SM2 when a sound is paused by the phone on sleep, for example.
