### ISSUE TITLE
Unclosed comment in nodebug script

### ISSUE THREAD

**Issue by scooper91** [scottschiller/SoundManager2#159]
There is an unclosed comment here, which is breaking our build: https://github.com/scottschiller/SoundManager2/blob/master/script/soundmanager2-nodebug.js#L14

**Comment by scottschiller** [comment]
Gah! My apologies, I must have broken this while doing a large refactor and didn't update my antiquated build process. Will look into this tonight. Thanks. 🙇

**Comment by scottschiller** [comment]
As needed, you can run the main `soundmanager2.js` through a minifier and get similar results - the `-nodebug` and `-nodebug-jsmin` are just "optimized" in that they remove blocks of code that output debug info to the console. SM2 doesn't normally log much anyway unless `?debug=1` or `debugMode` is enabled, but those builds just remove the lines entirely.

**Comment by scottschiller** [comment]
This is now fixed; thanks for the report!

This has been pushed to npm as `2.97.20170602` because you can't `--force` or update an existing release with the same revision number.

https://github.com/scottschiller/SoundManager2/commit/f432aa9ed96a0f9022e72fc4a1b977ba0643ed71

**Comment by scooper91** [comment]
Great, that was quick!  Thanks!
