### ISSUE TITLE
GA events and BarUI player

### ISSUE THREAD

**Issue by RobertBozic** [scottschiller/SoundManager2#193]
Hello, 
can anyone help me with advice and  information
how to monitor soundmanager BAR UI player events (play, pause...)
with Google analytics (analytics.js). 
Thanks
Robert

**Comment by scottschiller** [comment]
You'll want to hook into the events provided within the Bar UI script. From there, you can make calls to GA to log the event and details.

From `bar-ui.js`, an example:

```
/**
 * The following are player object event callback examples.
 * Override globally by setting window.sm2BarPlayers.on = {}, or individually by window.sm2BarPlayers[0].on = {} etc.
 * soundObject is provided for whileplaying() etc., but playback control should be done via the player object.
 */

/*
players.on = {

  play: function(player, soundObject) {
    console.log('playing', player);
  },

  whileplaying: function(player, soundObject) {
    console.log('whileplaying', player, soundObject);
  },
    
  finish: function(player, soundObject) {
    // each sound
    console.log('finish', player);
  },
    
  pause: function(player, soundObject) {
    console.log('pause', player);
  },

  error: function(player, soundObject) {
    console.log('error', player);
  },
  
  end: function(player, soundObject) {
    // end of playlist
    console.log('end', player);
  }
  
};
*/
```

**Comment by RobertBozic** [comment]
Thanks, 
for **play** event work like charm:

`    play: function(player, soundObject) {
      console.log('playing', player);
	  ga('send', 'event', 'Audio', 'play', soundObject.url);
    }`

Which event must I used to track 
playback duration if
the visitor leaves the page with the player?
Neither **end** nor **finish** not work in this case...
Have a nice Sunday!
