### ISSUE TITLE
Bar-UI single stream, autoplay

### ISSUE THREAD

**Issue by gmorks** [scottschiller/SoundManager2#201]
I'm integrating soundmanager to an amateur online radio station web page, everything works, but can't find a way to start the audio as soon as the web page ends loading. Can anyone guide me how to do it?

**Comment by scottschiller** [comment]
Howdy. Auto-play has been blocked on mobile devices for years, in desktop Safari more recently, and it's about to be blocked in Chrome on desktop - so my suggestion is that you have a "tap to play" or similar big play button that users can click / touch to start playback.

A bit more detail yonder.
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by gmorks** [comment]
ok, thank you for the reply

**Comment by Lazey5** [comment]
4a4e43f

**Comment by Lazey5** [comment]
Russian
