### ISSUE TITLE
iOS Firefox/Chrome/Safari returns "Unhandled Promise Rejection: NotAllowedError" when I attempt to play sound

### ISSUE THREAD

**Issue by wfsmith** [scottschiller/SoundManager2#225]
This just came up over the last few days. We have a production reactjs radio website that uses SoundManager2.  Users began reporting playback issues on mobile.  On debugging it, I am seeing the following error in Safari (using remote debugging but I presume the audio problems in Firefox Focus and Chrome are also caused by the same issue.

Essentially our radio website cannot play audio at the moment on iOS. I have not tested Android devices.  Any help would be greatly appreciated!

```
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed 
by the user agent or the platform in the current context, possibly because 
the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (Anonymous Script 1 (line 2129))
	fadeIn (Anonymous Script 2 (line 279))
	play (Anonymous Script 2 (line 206))
	load (Anonymous Script 2 (line 162))
	componentDidUpdate (Anonymous Script 2 (line 323))
	componentDidUpdate
	measureLifeCyclePerf (Anonymous Script 3 (line 73))
	(anonymous function) (Anonymous Script 3 (line 726))
	notifyAll (Anonymous Script 4 (line 74))
	close (Anonymous Script 5 (line 78))
	closeAll (Anonymous Script 6 (line 207))
	perform (Anonymous Script 6 (line 154))
	perform (Anonymous Script 6 (line 141))
	flushBatchedUpdates (Anonymous Script 7 (line 170))
	flushBatchedUpdates
	closeAll (Anonymous Script 6 (line 207))
	perform (Anonymous Script 6 (line 154))
	enqueueUpdate (Anonymous Script 7 (line 198))
	enqueueUpdate (Anonymous Script 8 (line 22))
	enqueueSetState (Anonymous Script 8 (line 216))
	setState (Anonymous Script 9 (line 62))
	onStoreChange (Anonymous Script 10 (line 53))
	(anonymous function)
	emit (Anonymous Script 11 (line 150))
	emitChange (Anonymous Script 12 (line 73))
	onRequestAudioAction (Anonymous Script 13 (line 80))
	onRequestAudioAction
	callHandler (Anonymous Script 14 (line 67))
	handlersEach (Anonymous Script 14 (line 45))
	forEach
	execute (Anonymous Script 14 (line 44))
	dispatch (Anonymous Script 15 (line 111))
	dispatch
	requestAudioAction (Anonymous Script 16 (line 10))
	(anonymous function) (Anonymous Script 17 (line 21))
	exports (Anonymous Script 18 (line 5))
	(anonymous function) (Anonymous Script 19 (line 35))
	run (Anonymous Script 19 (line 21))
	listener (Anonymous Script 19 (line 25))
[Log] sound-livestream: loadstart
[Log] sound-livestream: suspend
[Log] sound-livestream: durationchange (null)
[Log] sound-livestream: loadedmetadata
```

**Comment by pallavi1993** [comment]
Even am facing the same issue but only with safari. if you have found some solution please let me know.

**Comment by wfsmith** [comment]
@pallavi1993 I was not able to identify the actual cause, but we noticed a small discrepancy in webpack versions between a working and non-working version. So we rolled back webpack to an earlier version, recompiled, and the audio issue went away.

**Comment by pallavi1993** [comment]
Thank you so much. Will look into it and confirm you again.

**Comment by pallavi1993** [comment]
Hi @wfsmith , hereby am attaching the screenshot of how the logs are coming. You can check the same link in google chrome for its working.

You can check for the error at [http://18.234.38.144](http://18.234.38.144)

![safari error](https://user-images.githubusercontent.com/24584326/48043975-6c760380-e1af-11e8-9263-aa05e54b851b.png)

Please help me.

**Comment by pallavi1993** [comment]
Once the music starts, the music player should show me a blue bar, eventhough blue-bar is not coming am unable to hear any music.

**Comment by scottschiller** [comment]
@pallavi1993: Thanks for the screenshot. I wager your case _might_ have something to do with
1) Opening a pop-up window? (This is pretty "old-skool" and not recommended.)
2) Trying to auto-play audio in the pop-up. Browsers block pop-ups and auto-play these days.

The user is likely going to need to click to start audio playback in that pop-up window, so you will need another button there.

@wfsmith: Any chance your click handlers have become asynchronous or something? Safari is likely blocking what it thinks is "auto-play" or any `setTimeout()` or related delay between user action (click or touch etc.) and attempting to start playback of audio.

**Comment by wfsmith** [comment]
@scottschiller, yes this is what I suspect. But why a very minor Webpack version causes this, I have no idea.  The app is ancient by react/webpack standards. It uses Webpack v1.x and there was no package lock file so when we moved it, and installed it, the webpack version changed from something crazy minor like 1.21 to 1.22 or something.  There were a dozen or so package updates and I rolled them back one at a time until I proved the webpack to be the cause. 

 I can only guess some part of the rube goldberg machine was changed by the newer version of webpack that caused it to fail Apple's async autoplay/async check. Again, this is version 1.2 or something so maybe a regression bug was introduced that was patched in a later version? Who knows.

Thank you so much for following up.  Cheers.

@pallavi1993 sorry I missed your comment. I apologize. I would have to see the code to help further I'm afraid, but I would start with what Scott recommends of course!

**Comment by scottschiller** [comment]
@wfsmith Again, sorry for the late follow-up; SM2 is pretty stable, so most of the time it's people running into auto-play / permissions issues and HTTP partial/range requests and other anomalies. 😬 

Sounds to me like yeah, something shifted from sync -> async in some way, like maybe even a DOM mutation observer was introduced between click -> play, that may be all it takes. Unfortunately, browsers' policies on media playback throw a bit of a wildcard into the whole situation.

**Comment by pallavi1993** [comment]
@wfsmith and @scottschiller, we have removed the popup part and now the music should start immediately when the user click on the play button.

But am still unable to listen to the music.

I have tried changing different version of sound manager but it was also not helpful.

We are also not allowing any autoplay.

**Comment by scottschiller** [comment]
Addressing Pallavi's report in a separate issue, let's keep discussion there. https://github.com/scottschiller/SoundManager2/issues/231
