### ISSUE TITLE
How to see ALL songs in SoundManager 2: Bar UI (so without vertical scrollbar)

### ISSUE THREAD

**Issue by kdeneve** [scottschiller/SoundManager2#233]
Hello
Someone knows where I can change in the code the height of the player to see all mp3 songs at once?
At the moment the maximum displayed songs is 4 with a vertical scrollbar at the right

Regards 
Kurt

**Comment by scottschiller** [comment]
This should be doable.

Try this, in the relevant CSS file:

```
.sm2-playlist-wrapper ul {
  max-height: initial;
}
```
(Or, just remove the `max-height` rule there entirely; the above just resets it.)

I _think_ that should do it, and the animation will open / collapse the full height of the playlist.
Alternately, you can try playing with the `max-height` values if you'd like to see more, but still have a scrollbar at some point. I recommend opening the playlist, then editing that value until it lines up nicely with the number of items you want.

**Comment by kdeneve** [comment]
Hello,
Thank you very much for your help.
I used the css code you mentioned as an overrule and it works!
I don't understand that I over looked this one :-)

Regards
Kurt
