### ISSUE TITLE
Add reorder and remove to bar-ui demo playlist

### ISSUE THREAD

**Issue by tchoulihan** [scottschiller/SoundManager2#67]
Hey @scottschiller , you could label this a feature request.

I'm building a music application built around the bar-ui demo:
https://github.com/scottschiller/SoundManager2/blob/master/demo/bar-ui/script/bar-ui.js
, and would like to add the functionality to be able to remove, and possibly reorder the playlist tracks. 

Right now my application is saving the playlist to a DB, and refilling them whenever the page is reloaded, but I have no way to remove tracks to prevent this list from growing!

The html seems to be mainly generated from this javascript, but I'd need a little more direction. From what I can gather, we need to not make the entire row the same clickable <a> tag and add more buttons, but I can't really tell how the thing is filled in that javascript above. 

This is the kind of reordering I had in mind:
http://jqueryui.com/sortable/

is this handled in the `handleClick(e)` method? Or more specifically, can you tell me where the whole row is being filled?

**Comment by scottschiller** [comment]
The Bar UI is based on having either static HTML representing a playlist when it starts, *or* JS creating and injecting markup via `.innerHTML` or similar trickery after-the-fact.

In the demos I provide, I have static HTML in the page so it works without JS, and so people can see how the structure works. That said, there's nothing preventing you from creating or modifying the playlist items using JS. Each item is an `<li>`, etc.

If you want to add sortable-type functionality, that will be your own prerogative as that's beyond the scope of the Bar UI player. The player just looks at a list of links, and decorates them accordingly with CSS classes to indicate "playing" state as it goes through the list; that's about it.

When the user clicks the "play" button (or an item in the playlist), the Bar UI begins playback of the respective MP3 (or other) sound link. When that item finishes, by default, the player will look for the next sibling link (i.e., next item in the playlist) and will play that. It's designed intentionally to be simple, and not make assumptions about the structure of the live playlist DOM which could change at any time.

The simplicity described is a *good* thing, as it means you could add reordering or dynamic changes like adding/removing of items and the Bar UI script should be able to handle it just fine.
