### ISSUE TITLE
mp3 duration error in IE9

### ISSUE THREAD

**Issue by wbpmrck** [scottschiller/SoundManager2#70]
hello,i found a strange error:
when play a mp3 file generate by **ffmepg**,it will be ok in chrome,but in ie9,the duration is much shorter.
>ps:the ffmepg version is newer in the IE9 version

I got the binary transformed and found the mp3 data format difference:
1.this is the ok mp3 data:
![image](https://cloud.githubusercontent.com/assets/1442515/7954255/5f34c63c-0a00-11e5-8312-d426cbec4b04.png)

2.and this is the error mp3 data:
![image](https://cloud.githubusercontent.com/assets/1442515/7954263/74552886-0a00-11e5-8c51-c3001179c8f4.png)

**Comment by scottschiller** [comment]
Interesting; looks like a difference in the way ID3 data is written.
I don't have any info beyond that, but perhaps the ID3 data includes some information about duration that IE 9 picks up and uses in that case.

You may be able to verify IE's decoding behaviour by loading the MP3 directly in the browser, and see what the inline player UI shows for duration.
