### ISSUE TITLE
sound manger player 360 with wordpress loop

### ISSUE THREAD

**Issue by egydes** [scottschiller/SoundManager2#73]
Hello guys

actually i am using sm2 in client web site as sound manger for web site , i am using in in multiple loops , the crazy matter that link plays in some rows and some none ?

the site have a debug console you can see here : 
http://dotsdev.com/sounds/

what the problem ? and how solve it , i try to search and play and i notice when some rows don't play , i go to wordpress editor and change or re-upload site again and it work why that happen in same local host  & online ?

thanks a lot

**Comment by egydes** [comment]
i have another question : it should the media file aka mp3  file be unique  as i using 3 file in home as demo ?

**Comment by scottschiller** [comment]
Ah, regarding some playing and not, you're correct - MP3 file names just need to be unique.

If you have some duplicate MP3 links on the page, try making the second one unique e.g. append `?v=2` or similar to the URL. The 360 player script will look at the URL first and if it finds an existing sound playing with that URL, it will pause or resume the link related to the first URL and not the one actually clicked. Sorry! ;)

**Comment by scottschiller** [comment]
Closing as resolved - follow up as needed if things aren't sorted.
