### ISSUE TITLE
Playback Rate

### ISSUE THREAD

**Issue by fyockm** [scottschiller/SoundManager2#75]
Is there some way to alter the playback rate of the audio? If so, I couldn't figure it out. HTML5 Audio supports playbackRate, but it was unclear how leverage that.

https://developer.mozilla.org/en-US/Apps/Build/Audio_and_video_delivery/WebAudio_playbackRate_explained

As a use case, I want to give the user an ability to choose 1.5x playback speed.

**Comment by scottschiller** [comment]
Pardon late reply, vacation! :smile:

I should add this as a property and method, for HTML5 only. Flash 8/9 don't have any native support for this, a crazy custom implementation of sound decoding would be required etc. (And Flash use is _effectively_ dead for SM2 anyway, since nearly all clients do 100% HTML5 these days.)

The implementation would be simple, something like
`mySound.setPlaybackRate(1.5);`
`soundManager.setPlaybackRate('mySound', 1.5);`

... Will look at this shortly.

**Comment by kirensiva** [comment]
Is playbackrate supported in Android browsers?

**Comment by scottschiller** [comment]
Not sure what the support status is for `playbackrate` on Android. SM2 will try to use it, but it is ultimately up to the device/browser to apply the rate during playback - and I don't believe there is any way to reliably test it. _Maybe_ you could inspect the `Audio()` object for a `playbackrate` property, but it's likely that browsers will implement it and simply not do anything with it simply to provide compatibility with standard JS/audio APIs.

**Comment by ianbelanger** [comment]
Will you be releasing a new version with the setPlaybackRate() method? If yes, any idea when?

**Comment by scottschiller** [comment]
@ianbelanger I added it in my commit above, see https://github.com/scottschiller/SoundManager2/commit/7d5e24ac38356e18efe91bc01e159f24bf2dd898 for the addition.

This just tacks it on as an option, and adds `setPlaybackRate()` methods. Support will vary by browser/device, as it's an HTML5-native feature.

I'll have this out officially with the next release, but there's no harm in you grabbing and using the latest development version for now.

**Comment by fyockm** [comment]
Thanks @scottschiller!

**Comment by Developer-wp** [comment]
i need help

Uncaught ReferenceError: makeSound is not defined
    at Object.getAll (bar-ui.js:87)
    at bar-ui.js:2
    at processOnEvents (soundmanager2.js:260)
    at soundmanager2.js:263

**Comment by vmasto** [comment]
Hello, is this feature stable and shipped? It's not on the docs, can it be relied upon?

**Comment by joshketellapper** [comment]
ditto - I could really use this

**Comment by scottschiller** [comment]
@vmasto, @joshketellapper: I totally missed this thread with the last round of updates, apologies! `setPlaybackRate()` was added to SM2 with V2.97a.20170601. http://www.schillmania.com/projects/soundmanager2/doc/download/#sm2-20170601
