### ISSUE TITLE
Track progress problems with chromium/chrome, but not with firefox

### ISSUE THREAD

**Issue by tchoulihan** [scottschiller/SoundManager2#79]
When using the bar-ui example, and playing a song, I'm unable to seek halfway through the song with chromium, although it does work fine on firefox.

What could be the cause of this?

edit: I also just tested out safari, and it neither updates the track progress, nor can skip to any part of the song.

**Comment by scottschiller** [comment]
Is this from the live demo site? In either case, it's worth noting that HTML5 clients are picky about how they request audio resources; HTTP response headers matter. The following link may provide some context.
http://www.schillmania.com/projects/soundmanager2/doc/technotes/#serving-audio

My server (for the demos) should be configured properly for current HTML5 audio clients. I haven't had problems with the demos from the live SM2 homepage.

Which version of Safari are you getting this on? If you're on a prerelease or nightly etc., that'll be good to know.

**Comment by tchoulihan** [comment]
Sorry, I should've closed this earlier. I spent 2 frustrating days on this weird problem, but verified in the end that it had to do with content-headers. I was serving the file up from an embedded jetty instance, not from a typical apache server, and there are a lot of gotchas when you do that.
