### ISSUE TITLE
Sound paused but playstate is 1

### ISSUE THREAD

**Issue by kanbekotori** [scottschiller/SoundManager2#81]
I use the lasted version.
console
------------------------
display  | file
------------- | -------------
agmusic0: pause()  | soundmanager2-jsmin.js:34
1  | app-player.js:122

code
------------------------
```
Player.prototype.playing = function() {
    console.log(playSong.playState)
    return playSong != null && playSong.playState == 1;
 }

onPause: function() {
  player.playing();
}
```

**Comment by scottschiller** [comment]
`playState` is correctly 1 when a sound is playing, or paused. It is 0 when the sound is uninitialized - that is, it has not playing or paused.
http://www.schillmania.com/projects/soundmanager2/doc/#smsound-playstate

When paused, a sound should have its `paused` property set to `true` while `playState` will be 1. When a sound is stopped (or before loading etc.), `playState` will be 0.

If you feel there's something missing, let me know - but this behaviour should be correct.
