### ISSUE TITLE
Cannot read property 'type' of undefined !

### ISSUE THREAD

**Issue by egydes** [scottschiller/SoundManager2#82]
i am using soundmanager2 library it was working perfect on old hosting when i move the site to another host give me error on debug console

Cannot read property 'type' of undefined

and the player button doesn't appear ?

how can i solve that ?

**Comment by scottschiller** [comment]
If you have a demo available I can look at, I may be able to help troubleshoot further. Perhaps some of the JS just isn't loading.

Otherwise, you might have some luck in upgrading to the latest version of SM2.

**Comment by scottschiller** [comment]
Closing out old bug! V2.97a.20170601 is out, suggest taking a look if you still use it. 👌
