### ISSUE TITLE
Can't play aacp shoutcast stream

### ISSUE THREAD

**Issue by ugjka** [scottschiller/SoundManager2#86]
Is playing live streams supported?

I can make shoutcast streams that serve mp3 play fine

But when I try to load a stream that serves HE-AACv2 (aka aac plus) I get no sound

Example stream "http://lr4mp1.latvijasradio.lv:8020/;"

Header: 
0000:0000 | 49 43 59 20  32 30 30 20  4F 4B 0D 0A  69 63 79 2D | ICY 200 OK..icy-
0000:0010 | 6E 6F 74 69  63 65 31 3A  3C 42 52 3E  54 68 69 73 | notice1:<BR>This
0000:0020 | 20 73 74 72  65 61 6D 20  72 65 71 75  69 72 65 73 |  stream requires
0000:0030 | 20 3C 61 20  68 72 65 66  3D 22 68 74  74 70 3A 2F |  <a href="http:/
0000:0040 | 2F 77 77 77  2E 77 69 6E  61 6D 70 2E  63 6F 6D 2F | /www.winamp.com/
0000:0050 | 22 3E 57 69  6E 61 6D 70  3C 2F 61 3E  3C 42 52 3E | ">Winamp</a><BR>
0000:0060 | 0D 0A 69 63  79 2D 6E 6F  74 69 63 65  32 3A 53 48 | ..icy-notice2:SH
0000:0070 | 4F 55 54 63  61 73 74 20  44 69 73 74  72 69 62 75 | OUTcast Distribu
0000:0080 | 74 65 64 20  4E 65 74 77  6F 72 6B 20  41 75 64 69 | ted Network Audi
0000:0090 | 6F 20 53 65  72 76 65 72  2F 77 69 6E  33 32 20 76 | o Server/win32 v
0000:00A0 | 31 2E 39 2E  38 3C 42 52  3E 0D 0A 69  63 79 2D 6E | 1.9.8<BR>..icy-n
0000:00B0 | 61 6D 65 3A  52 61 64 69  6F 20 34 0D  0A 69 63 79 | ame:Radio 4..icy
0000:00C0 | 2D 67 65 6E  72 65 3A 0D  0A 69 63 79  2D 75 72 6C | -genre:..icy-url
0000:00D0 | 3A 68 74 74  70 3A 2F 2F  6C 72 34 2E  6C 61 74 76 | :http://lr4.latv
0000:00E0 | 69 6A 61 73  72 61 64 69  6F 2E 6C 76  0D 0A 63 6F | ijasradio.lv..co
0000:00F0 | 6E 74 65 6E  74 2D 74 79  70 65 3A 61  75 64 69 6F | ntent-type:audio
0000:0100 | 2F 61 61 63  70 0D 0A 69  63 79 2D 70  75 62 3A 30 | /aacp..icy-pub:0
0000:0110 | 0D 0A 69 63  79 2D 62 72  3A 34 38 0D  0A 0D 0A 4D | ..icy-br:48....M`

**Comment by ugjka** [comment]
Just tested I can play aac plus audio from a file so my guess is soundmanager doesn't like streams with no end

**Comment by ugjka** [comment]
Ok got it working by setting 

`type: 'audio/aac'`

closing

**Comment by ugjka** [comment]
If I set type to audio/aac on this stream soundmanager won't use flash even when I have prefer flash to true. I pretty sure flash can handle aac plus streams and I need flash for firefox because it can't play aac  plus streams via html5.

I tried setting type to audio/mp4 but then flash complained
`"(Flash): netStatusEvent: NetStream.Play.StreamNotFound" soundmanager2.js:1295:9`

**Comment by ugjka** [comment]
Ugh, aac plus audio plays nice in firefox both in html5 and flash when they are in a proper mp4 container. It seems the problem here is pure aac streams.

**Comment by scottschiller** [comment]
AAC is a bit of a complex beast as you've found, the MPEG-4 container can be confusing at best.

"Flash Player 9 Update 3" introduced MPEG-4 support (video and audio), and a tech note on the basic format support is yonder.
https://helpx.adobe.com/flash/kb/supported-codecs-flash-player.html

ShoutCast, IceCast and the like seem to present a few additional challenges to Flash from what I've found - sometimes it can be picky and doesn't like the extra metadata in the stream, etc. When possible, HTML5 seems to be much better about handling these pseudo-streaming servers.

**Comment by ugjka** [comment]
Thanks for the reply

In pure html 5 solution Chrome is the only browser that fully supports Shoutcast and Icecast with both mp3 and aac streams

* Firefox can handle only mp3 live-streams
* IE doesn't like shoutcast at all

And some linux browsers like qupzilla will even crash.

At this time I'll do browser sniffing and simply hide unsupported streams or simply warn users to install chrome.

**Comment by scottschiller** [comment]
Sounds like the best option at this time; sorry it isn't easier. :grimacing:
