### ISSUE TITLE
SoundManager2 doesn't play nice with webcomponents.js

### ISSUE THREAD

**Issue by ugjka** [scottschiller/SoundManager2#87]
Having both
`<script src="bower_components/soundmanager2/script/soundmanager2.js"></script>`
and
`<script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>`
with 
`preferFlash: true`

will cause

`"js/flash exception: TypeError: flash._externalInterfaceTest is not a function"`
`"soundManager.disable(): Shutting down"`
`"SoundManager 2 failed to load (Flash security/load error) ✖"`

Happens in every browser (Firefox, IE 9, Qupzilla) except Chrome and its derivatives

If preferFlash is false, soundmanager loads fine

**Comment by scottschiller** [comment]
Thanks for the report, sounds like something is breaking the JS/Flash interface bridge.

**Comment by scottschiller** [comment]
Sorry I don't have an update for this. :frowning: I've confirmed the issue with webcomponents, but I don't have an answer as to what's going on. Seems like something is interfering with the way the Flash plugin adds the ExternalInterface bridge.

Flash -> JS may be an edge case, but something that webcomponents should not break.

**Comment by ugjka** [comment]
I think we can close this since no one really uses flash anymore.
In fact I can't even make it flash to work with flashPrefer true

**Comment by QWp6t** [comment]
Adobe acknowledged today that browsers have been winding down Flash support and Adobe will be pulling the plug on Flash within the next 3 years.

sauce: https://www.theverge.com/2017/7/25/16026236/adobe-flash-end-of-support-2020

**Comment by scottschiller** [comment]
Indeed! I updated http://isflashdeadyet.com/ recently, accordingly. :D Thanks for the reminder.
SM2 should still work with `preferFlash: true`, provided that the Flash plugin is installed and is not blocked etc.
