### ISSUE TITLE
_destroySound not a function

### ISSUE THREAD

**Issue by OpenGrid** [scottschiller/SoundManager2#90]
V2.97a.20140901

I get _destroySound not a function error in userAgent: Mozilla/5.0 (X11; Linux i686; rv:18.0) Gecko/20100101 Firefox/18.0
Maybe this code should check if `flash` is still an object with _destroySound method

``` javascript
if (!s.isHTML5) {
  // kill sound within Flash
  // Disable the onfailure handler
  s._iO.onfailure = null;
  flash._destroySound(s.id);
}
```

...
same here, _pause is not defined when flash is not available

``` javascript
if (!s.isHTML5) {
    if (_bCallFlash || _bCallFlash === _undefined) {
    flash._pause(s.id, s._iO.multiShot);
  }
}
```

**Comment by scottschiller** [comment]
Thanks for the note, sorry for the late follow-up.
Is there any chance something is stopping and/or reinitializing the flash plugin in your particular case?
The current release is May 2015 also, but I suspect it will have the same issue.
Let me know if you are able to reproduce this on one of the SM2 demo pages, e.g., [demo 6](http://www.schillmania.com/projects/soundmanager2/demo/api/#create-play-unload-destroy).

**Comment by OpenGrid** [comment]
Is it possible that addons like Adblock would do that? Anyway I think this should be wrapped in some internal error reporting that flash object is no longer defined.

**Comment by scottschiller** [comment]
V2.97a.20170601 is now out; I don't think there are any sweeping updates that would cover the flash disappearing case, but it's worth an update if you still use SM2, and let me know if you run into this. My comment from almost two years ago (ha! 👴) may still apply, re: `display` or `innerHTML` overwrites causing the Flash movie to get nuked or reset. Those are common ways for the element to get dropped.
