### ISSUE TITLE
Playback doesnt start after buffering on mobile browsers. 

### ISSUE THREAD

**Issue by dessalines** [scottschiller/SoundManager2#93]
I'm using the bar ui demo in my application:

http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/

For some reason, after clicking play on my mobile browser, the song appears to buffer(shows the circle spinner) , but then doesn't start playing. I have to click pause then play again, and it will start. 

You can confirm this bug by going to the link above on any mobile browser.

**Comment by tchoulihan** [comment]
Really needing some help with this, I'm at a dead end. I've also noticed auto-playing doesn't work on mobile...

**Comment by scottschiller** [comment]
Howdy! Thanks for the PR, and sorry for the late follow-up.

One note - it's best to assume mobile devices will not allow auto-play by default; it is blocked at the browser/OS level similar to how pop-up blockers work, in that user interaction such as a touch or click event is required to initiate the action. Calls must be synchronous; a `play()` within a `setTimeout()` et al will fail.

What device / OS version, etc., are you experiencing this issue on? I have an iPhone 6 with iOS 8.4.1, and the demo seems to work OK for me - clicking the play button results in playback starting, etc.

**Comment by scottschiller** [comment]
Closing out this issue before its second birthday. 😉 V2.97a.20170601 is out, let me know if you still use SM2 and run into this issue. Auto-play is still blocked on mobile devices (by the device's OS), and it's not recommended you try to work around it.
