### ISSUE TITLE
Is posible to play a local sound ?

### ISSUE THREAD

**Issue by nhattuanbl** [scottschiller/SoundManager2#96]
Is posible to play a local sound, ex: D:/Music/file.mp3. Thank

**Comment by stevmark61** [comment]
Depends...

No, if you're using Flash you need to run soundManager from a server, local or remote due to Flash's security limitations.

Yes. Using HTML5 Audio but the sound will only be reproduced through a browser on the local computer where the sound resides..

**Comment by scottschiller** [comment]
I haven't tried this myself, but someone reported success loading from `file://` when using some of the newer File APIs and providing the URL returned from the file API to SM2, when running in HTML5 mode.

https://getsatisfaction.com/schillmania/topics/unable-to-play-a-local-files-using-file
