### ISSUE TITLE
No ability of creating multiple library objects with different settings

### ISSUE THREAD

**Issue by unel** [scottschiller/SoundManager2#99]
=(

**Comment by scottschiller** [comment]
Pardon the late reply here - but I'm going to need more detail. Can you explain what you mean by "multiple library objects"?

If you are creating sound objects via `createSound()`, you can provide different parameters and each sound object created will have its own unique settings.

**Comment by scottschiller** [comment]
Closing after 1.5+ years of 💤. If you can clarify "multiple library objects" and settings, perhaps I can help!
